# Generated by Django 2.2.6 on 2020-04-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailypost',
            name='autotask',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dailypost',
            name='todaytask',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dailypost',
            name='tomorrowtask',
            field=models.TextField(),
        ),
    ]
